version: '3.8'

services:

  server:
    image: yujiro2hanma/crashtrace-server:latest
    container_name: crash-trace-server
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASS=${MAIL_PASS}
      - JWT_SECRET=${JWT_SECRET}
